apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: imup
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: edev=crmasraf001.azurecr.io/enhanced-devops
    argocd-image-updater.argoproj.io/edev.allow-tags: regexp:^dev-[a-zA-Z0-9]*$
    argocd-image-updater.argoproj.io/edev.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/edev.pull-secret: acr-cred
spec: 
  project: default
  source: 
    repoURL: https://github.com/xokacar/imup-middle
    path: ./imupchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
    - Force=true
    - Validate=false
    - CreateNamespace=true
    - PruneLast=true