apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: imup
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/write-back-target: helm
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: "enhanced-devops=crmasraf001.azurecr.io/enhanced-devops:latest"
    argocd-image-updater.argoproj.io/enhanced-devops.update-strategy: latest
    argocd-image-updater.argoproj.io/enhanced-devops.force-update: "true"
    argocd-image-updater.argoproj.io/enhanced-devops.allow-tags: regexp:^v1.0.0-[0-9a-zA-Z]+$
spec: 
  project: default
  source: 
    repoURL: https://github.com/xokacar/imup-middle
    path: ./imupchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
    - Replace=true
    automated:
      prune: true
      selfHeal: true

     