apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: imup
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:secret/git-credentials
    argocd-image-updater.argoproj.io/image-list: "enhanced-devops=crmasraf001.azurecr.io/enhanced-devops:latest"
    argocd-image-updater.argoproj.io/enhanced-devops.update-strategy: latest
    argocd-image-updater.argoproj.io/enhanced-devops.allow-tags: regexp:^[0-9a-f]{7}$
spec: 
  project: default
  source: 
    repoURL: https://github.com/xokacar/imup-middle
    path: ./imupchart
    targetRevision: HEAD
    helm:
     valueFiles:
     - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true