apiVersion: v1
data:
  account.image-updater: apiKey
  application_api: argocd
  argocd.grpc_web: "true"
  argocd.insecure: "false"
  argocd.plaintext: "false"
  argocd.server.addr: 10.96.46.202
  kube.events: "false"
  log.level: debug
  registries.conf: |
    {
      "auths": {
        "crmasraf001.azurecr.io": {
          "auth": "{{ .secrets.acr-cred.auth }}"
        }
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"account.image-updater":"apiKey","application_api":"argocd","argocd.grpc_web":"true","argocd.insecure":"false","argocd.plaintext":"false","argocd.server.addr":"localhost:8080","kube.events":"false","log.level":"debug","registries.conf":"{\n  \"auths\": {\n    \"crmasraf001.azurecr.io\": {\n      \"auth\": \"{{ .secrets.acr-cred.auth }}\"\n    }\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"argocd-image-updater","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2023-11-19T16:40:37Z","labels":{"app.kubernetes.io/instance":"argocd-image-updater","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argocd-image-updater","app.kubernetes.io/version":"v0.12.2","helm.sh/chart":"argocd-image-updater-0.9.1"},"name":"argocd-image-updater-config","namespace":"default","resourceVersion":"309914","uid":"8c32b8ec-c735-44e1-8c5a-434d647b8454"}}
    meta.helm.sh/release-name: argocd-image-updater
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-11-19T16:40:37Z"
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/version: v0.12.2
    helm.sh/chart: argocd-image-updater-0.9.1
  name: argocd-image-updater-config
  namespace: default
  resourceVersion: "1616884"
  uid: 8c32b8ec-c735-44e1-8c5a-434d647b8454
